name: TrueWidget

options:
  bundleIdPrefix: org.pqrs

targets:
  TrueWidget:
    type: application
    platform: macOS
    deploymentTarget: '11.0'
    sources:
      - path: TrueWidget
        compilerFlags:
          - '-Wall'
          - '-Werror'
        excludes:
          - 'objc/*'
          - 'Info.plist.in'
      - path: TrueWidget/objc
        compilerFlags:
          - '-Wall'
          - '-Werror'
          - '-Wno-deprecated-declarations'
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: ''
        SWIFT_OBJC_BRIDGING_HEADER: TrueWidget/objc/Bridging-Header.h
