name: TrueWidget

options:
  bundleIdPrefix: org.pqrs

targets:
  TrueWidget:
    type: application
    platform: macOS
    deploymentTarget: '11.0'
    sources:
      - path: TrueWidget
        compilerFlags:
          - '-Wall'
          - '-Werror'
        excludes:
          - 'Info.plist.in'
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: ''
